### PR TITLE
Fix incorrect warning

### LINKED ISSUE #97: Incorrect warning: "vnet is enabled"
### Your environment.
  - Version: v1.3.6
  - Browser: n/a

### What did you do?
Ran my app using pion/turn with PION_LOG_WARN=all

### What happened?

I see this warning even though vnet is not enabled
```
turnc WARNING: 2019/09/21 19:48:15 vnet is enabled
```

### PR DESCRIPTION
**Pull request by enobufs**
Resolves #97

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -78,7 +78,7 @@ func NewClient(config *ClientConfig) (*Client, error) {
 
 	if config.Net == nil {
 		config.Net = vnet.NewNet(nil) // defaults to native operation
-	} else {
+	} else if config.Net.IsVirtual() {
```
Comment (hugoArregui) [inline client.go]: should we do this for ice as well? (https://github.com/pion/ice/blob/master/agent.go#L345)

Comment (enobufs) [reply client.go]: Yes, I have [this commit](https://github.com/pion/ice/pull/103/commits/844561e47b58c47b1c95c9c5dd90219fb31c56ad)
